language: bash
services: docker

env:
  - VERSION=6.0 DIST=debian REL=stretch
  - VERSION=6.0 DIST=alpine REL=3.8
  - VERSION=6.2 DIST=debian REL=stretch
  - VERSION=6.2 DIST=alpine REL=3.8

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/${DIST}/${REL}"
  - image="varnish:${VERSION}-${DIST}-${REL}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
