#!/bin/sh
set -e

dir=/usr/src/varnish

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Manage varnish source tarball lifecycle."
	echo
	echo "Commands:"
	echo "   extract  extract varnish source tarball into directory $dir if not already done."
	echo "   delete   delete extracted varnish source located into $dir if not already done."
	echo
}

case "$1" in
	extract)
		mkdir -p "$dir"
		if [ ! -f "$dir/.docker-extracted" ]; then
			tar -zxf /usr/src/varnish.tar.gz -C "$dir" --strip-components=1
			touch "$dir/.docker-extracted"
		fi
		;;

	delete)
		rm -rf "$dir"
		;;

	*)
		usage
		exit 1
		;;
esac
